" Spy patrol data for this level
" Generated by tools/level_builder.py - do not edit manually
" Format: Vim list - use eval(join(readfile(...), "")) to parse
[{'id': 'patrol_top', 'spawn': [5, 10], 'route': [{'end': [5, 35], 'dir': 'right'}, {'end': [5, 10], 'dir': 'left'}], 'speed': 0.6},{'id': 'patrol_bottom', 'spawn': [8, 35], 'route': [{'end': [8, 10], 'dir': 'left'}, {'end': [8, 35], 'dir': 'right'}], 'speed': 0.7}]